feat: add xPadding
mljs/spectra-processing pull request #14
Opened 2020-10-08 14:49 UTC by lpatiny

2020-10-08 15:04 UTC, kjappelbaum requested changes
looks good to me, I think we should fix the doc string before merging.

2020-10-08 15:04 UTC, kjappelbaum commented on src/x/xPadding.js
> +  let result = new Float64Array(array.length + size * 2);
Maybe we can validate the input with `import xCheck from './xCheck';`
```suggestion
  xCheck(array);
  let result = new Float64Array(array.length + size * 2);
```

2020-10-08 15:18 UTC, lpatiny commented
@kjappelbaum Many thanks for your review !

2020-10-08 15:18 UTC, merged

2021-02-15 09:21 UTC, kjappelbaum commented
I think one should reuse https://github.com/mljs/pad-array i just saw it and it is probably better to not maintain the code in two places.